import React, { memo } from 'react';
import { useTranslation } from 'react-i18next';
import { collection, setDoc, doc } from 'firebase/firestore';
import { Page } from '@/widgets/Page';
import { ArticleRating } from '@/widgets/StatisticsCharts';
import { firestore } from '../../../../json-server/firebase';

const ratingsCollection = collection(firestore, 'ratings');

const ratings = [
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '40',
        rate: 5,
        id: '101',
    },
    {
        userId: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
        articleId: '40',
        rate: 4,
        id: '102',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '40',
        rate: 4,
        id: '103',
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '40',
        rate: 3,
        id: '104',
    },
    {
        userId: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
        articleId: '40',
        rate: 5,
        id: '105',
    },
    {
        userId: 'meuKZ9Dc5ucUuMn72esjwMi9Azl2',
        articleId: '40',
        rate: 3,
        id: '106',
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '40',
        rate: 4,
        id: '107',
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '40',
        rate: 5,
        id: '108',
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '40',
        rate: 4,
        id: '109',
    },
    {
        userId: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
        articleId: '40',
        rate: 4,
        id: '110',
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '40',
        rate: 3,
        id: '111',
    },
    {
        userId: '4juq0tzGf5fNMCXCRFOa5mvFO5O2',
        articleId: '40',
        rate: 4,
        id: '112',
    },
    {
        userId: '9Dpc2pFoeORLyQrxHlGIbe5wjbf2',
        articleId: '40',
        rate: 5,
        id: '113',
    },
    {
        userId: 'BrKES0pOcxcgYBUpKmZxBzqKFhl1',
        articleId: '40',
        rate: 3,
        id: '114',
    },
    {
        userId: 'Ue15ycXTpxVhCZ2eJoOVYaArKEa2',
        articleId: '40',
        rate: 4,
        id: '115',
    },
    {
        userId: 'KXv8oUPLQeUXSzoXOWJV4nw47CG2',
        articleId: '40',
        rate: 4,
        id: '116',
    },
    {
        userId: '18zZBJnmEqWJNwGj2SvbNiNVXol1',
        articleId: '40',
        rate: 5,
        id: '117',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '40',
        rate: 4,
        id: '118',
    },
    {
        userId: 'Str49JTKBAOoaEhM8XeQLLLPPDp2',
        articleId: '40',
        rate: 3,
        id: '119',
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '41',
        rate: 5,
        feedback: 'Another great article!',
        id: '120',
    },
    {
        userId: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
        articleId: '41',
        rate: 4,
        id: '121',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '41',
        rate: 4,
        id: '122',
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '41',
        rate: 3,
        id: '123',
    },
    {
        userId: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
        articleId: '41',
        rate: 5,
        id: '124',
    },
    {
        userId: 'meuKZ9Dc5ucUuMn72esjwMi9Azl2',
        articleId: '41',
        rate: 4,
        id: '125',
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '41',
        rate: 5,
        id: '126',
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '41',
        rate: 3,
        id: '127',
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '41',
        rate: 4,
        id: '128',
    },
    {
        userId: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
        articleId: '41',
        rate: 4,
        id: '129',
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '41',
        rate: 5,
        id: '130',
    },
    {
        userId: '4juq0tzGf5fNMCXCRFOa5mvFO5O2',
        articleId: '41',
        rate: 3,
        id: '131',
    },
    {
        userId: '9Dpc2pFoeORLyQrxHlGIbe5wjbf2',
        articleId: '41',
        rate: 4,
        id: '132',
    },
    {
        userId: 'BrKES0pOcxcgYBUpKmZxBzqKFhl1',
        articleId: '41',
        rate: 4,
        id: '133',
    },
    {
        userId: 'Ue15ycXTpxVhCZ2eJoOVYaArKEa2',
        articleId: '41',
        rate: 5,
        id: '134',
    },
    {
        userId: 'KXv8oUPLQeUXSzoXOWJV4nw47CG2',
        articleId: '41',
        rate: 3,
        id: '135',
    },
    {
        userId: '18zZBJnmEqWJNwGj2SvbNiNVXol1',
        articleId: '41',
        rate: 4,
        id: '136',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '41',
        rate: 4,
        id: '137',
    },
    {
        userId: 'Str49JTKBAOoaEhM8XeQLLLPPDp2',
        articleId: '41',
        rate: 3,
        id: '138',
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '62',
        rate: 5,
        id: '139',
    },
    {
        userId: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
        articleId: '62',
        rate: 4,
        id: '140',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '62',
        rate: 5,
        feedback: 'Loved the depth of this article',
        id: '141',
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '62',
        rate: 4,
        id: '142',
    },
    {
        userId: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
        articleId: '62',
        rate: 3,
        id: '143',
    },
    {
        userId: 'meuKZ9Dc5ucUuMn72esjwMi9Azl2',
        articleId: '62',
        rate: 4,
        id: '144',
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '62',
        rate: 3,
        id: '145',
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '62',
        rate: 4,
        id: '146',
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '62',
        rate: 5,
        id: '147',
    },
    {
        userId: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
        articleId: '62',
        rate: 4,
        id: '148',
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '62',
        rate: 3,
        id: '149',
    },
    {
        userId: '4juq0tzGf5fNMCXCRFOa5mvFO5O2',
        articleId: '62',
        rate: 4,
        id: '150',
    },
    {
        userId: '9Dpc2pFoeORLyQrxHlGIbe5wjbf2',
        articleId: '62',
        rate: 5,
        feedback: 'In-depth and insightful',
        id: '151',
    },
    {
        userId: 'BrKES0pOcxcgYBUpKmZxBzqKFhl1',
        articleId: '62',
        rate: 3,
        id: '152',
    },
    {
        userId: 'Ue15ycXTpxVhCZ2eJoOVYaArKEa2',
        articleId: '62',
        rate: 4,
        id: '153',
    },
    {
        userId: 'KXv8oUPLQeUXSzoXOWJV4nw47CG2',
        articleId: '62',
        rate: 5,
        id: '154',
    },
    {
        userId: '18zZBJnmEqWJNwGj2SvbNiNVXol1',
        articleId: '62',
        rate: 4,
        id: '155',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '62',
        rate: 4,
        id: '156',
    },
    {
        userId: 'Str49JTKBAOoaEhM8XeQLLLPPDp2',
        articleId: '62',
        rate: 3,
        id: '157',
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '141',
        rate: 5,
        id: '158',
    },
    {
        userId: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
        articleId: '141',
        rate: 4,
        id: '159',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '141',
        rate: 5,
        id: '160',
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '141',
        rate: 3,
        id: '161',
    },
    {
        userId: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
        articleId: '141',
        rate: 4,
        id: '162',
    },
    {
        userId: 'meuKZ9Dc5ucUuMn72esjwMi9Azl2',
        articleId: '141',
        rate: 4,
        id: '163',
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '141',
        rate: 3,
        id: '164',
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '141',
        rate: 4,
        id: '165',
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '141',
        rate: 5,
        id: '166',
    },
    {
        userId: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
        articleId: '141',
        rate: 4,
        id: '167',
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '141',
        rate: 4,
        id: '168',
    },
    {
        userId: '4juq0tzGf5fNMCXCRFOa5mvFO5O2',
        articleId: '141',
        rate: 4,
        id: '169',
    },
    {
        userId: '9Dpc2pFoeORLyQrxHlGIbe5wjbf2',
        articleId: '141',
        rate: 5,
        id: '170',
    },
    {
        userId: 'BrKES0pOcxcgYBUpKmZxBzqKFhl1',
        articleId: '141',
        rate: 3,
        id: '171',
    },
    {
        userId: 'Ue15ycXTpxVhCZ2eJoOVYaArKEa2',
        articleId: '141',
        rate: 4,
        id: '172',
    },
    {
        userId: 'KXv8oUPLQeUXSzoXOWJV4nw47CG2',
        articleId: '141',
        rate: 3,
        id: '173',
    },
    {
        userId: '18zZBJnmEqWJNwGj2SvbNiNVXol1',
        articleId: '141',
        rate: 5,
        id: '174',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '141',
        rate: 4,
        id: '175',
    },
    {
        userId: 'Str49JTKBAOoaEhM8XeQLLLPPDp2',
        articleId: '141',
        rate: 3,
        id: '176',
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '172',
        rate: 5,
        feedback: 'Outstanding piece!',
        id: '177',
    },
    {
        userId: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
        articleId: '172',
        rate: 4,
        id: '178',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '172',
        rate: 4,
        id: '179',
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '172',
        rate: 3,
        id: '180',
    },
    {
        userId: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
        articleId: '172',
        rate: 4,
        id: '181',
    },
    {
        userId: 'meuKZ9Dc5ucUuMn72esjwMi9Azl2',
        articleId: '172',
        rate: 5,
        id: '182',
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '172',
        rate: 4,
        id: '183',
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '172',
        rate: 3,
        id: '184',
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '172',
        rate: 4,
        id: '185',
    },
    {
        userId: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
        articleId: '172',
        rate: 5,
        id: '186',
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '172',
        rate: 4,
        id: '187',
    },
    {
        userId: '4juq0tzGf5fNMCXCRFOa5mvFO5O2',
        articleId: '172',
        rate: 3,
        id: '188',
    },
    {
        userId: '9Dpc2pFoeORLyQrxHlGIbe5wjbf2',
        articleId: '172',
        rate: 5,
        feedback: 'Really good content!',
        id: '189',
    },
    {
        userId: 'BrKES0pOcxcgYBUpKmZxBzqKFhl1',
        articleId: '172',
        rate: 4,
        id: '190',
    },
    {
        userId: 'Ue15ycXTpxVhCZ2eJoOVYaArKEa2',
        articleId: '172',
        rate: 3,
        id: '191',
    },
    {
        userId: 'KXv8oUPLQeUXSzoXOWJV4nw47CG2',
        articleId: '172',
        rate: 4,
        id: '192',
    },
    {
        userId: '18zZBJnmEqWJNwGj2SvbNiNVXol1',
        articleId: '172',
        rate: 5,
        id: '193',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '172',
        rate: 4,
        id: '194',
    },
    {
        userId: 'Str49JTKBAOoaEhM8XeQLLLPPDp2',
        articleId: '172',
        rate: 3,
        id: '195',
    },
    {
        userId: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
        articleId: '38',
        rate: 5,
        feedback: 'Very informative and well-structured',
        id: '201',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '38',
        rate: 4,
        id: '202',
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '38',
        rate: 3,
        id: '203',
    },
    {
        userId: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
        articleId: '38',
        rate: 4,
        feedback: 'Good overview, could use more examples',
        id: '204',
    },
    {
        userId: 'meuKZ9Dc5ucUuMn72esjwMi9Azl2',
        articleId: '38',
        rate: 5,
        id: '205',
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '38',
        rate: 4,
        id: '206',
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '38',
        rate: 4,
        id: '207',
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '38',
        rate: 5,
        id: '208',
    },
    {
        userId: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
        articleId: '38',
        rate: 3,
        id: '209',
    },
    {
        userId: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
        articleId: '39',
        rate: 4,
        id: '210',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '39',
        rate: 5,
        id: '211',
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '39',
        rate: 4,
        id: '212',
    },
    {
        userId: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
        articleId: '39',
        rate: 3,
        id: '213',
    },
    {
        userId: 'meuKZ9Dc5ucUuMn72esjwMi9Azl2',
        articleId: '39',
        rate: 4,
        feedback: 'Well explained, clear examples',
        id: '214',
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '39',
        rate: 5,
        id: '215',
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '39',
        rate: 3,
        id: '216',
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '39',
        rate: 5,
        id: '217',
    },
    {
        userId: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
        articleId: '39',
        rate: 4,
        feedback: 'Great insights, could cover more edge cases',
        id: '218',
    },
    {
        userId: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
        articleId: '61',
        rate: 4,
        id: '219',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '61',
        rate: 5,
        feedback: 'One of the best articles on this topic!',
        id: '220',
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '61',
        rate: 4,
        id: '221',
    },
    {
        userId: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
        articleId: '61',
        rate: 3,
        id: '222',
    },
    {
        userId: 'meuKZ9Dc5ucUuMn72esjwMi9Azl2',
        articleId: '61',
        rate: 5,
        id: '223',
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '61',
        rate: 4,
        id: '224',
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '61',
        rate: 4,
        feedback: 'Solid article, well done',
        id: '225',
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '61',
        rate: 3,
        id: '226',
    },
    {
        userId: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
        articleId: '61',
        rate: 4,
        id: '227',
    },
    {
        userId: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
        articleId: '105',
        rate: 5,
        feedback: 'Excellent depth of coverage',
        id: '228',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '105',
        rate: 4,
        id: '229',
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '105',
        rate: 4,
        id: '230',
    },
    {
        userId: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
        articleId: '105',
        rate: 3,
        id: '231',
    },
    {
        userId: 'meuKZ9Dc5ucUuMn72esjwMi9Azl2',
        articleId: '105',
        rate: 4,
        id: '232',
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '105',
        rate: 5,
        id: '233',
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '105',
        rate: 4,
        id: '234',
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '105',
        rate: 4,
        id: '235',
    },
    {
        userId: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
        articleId: '105',
        rate: 3,
        id: '236',
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '37',
        rate: 5,
        feedback: 'Excellent explanation and very detailed. Helped me a lot!',
        id: '237',
    },
    {
        userId: '4juq0tzGf5fNMCXCRFOa5mvFO5O2',
        articleId: '37',
        rate: 4,
        feedback:
            'Great article, clear and concise. Could include more examples.',
        id: '238',
    },
    {
        userId: '9Dpc2pFoeORLyQrxHlGIbe5wjbf2',
        articleId: '37',
        rate: 5,
        feedback: 'Well-written and informative, definitely a must-read!',
        id: '239',
    },
    {
        userId: 'BrKES0pOcxcgYBUpKmZxBzqKFhl1',
        articleId: '37',
        rate: 4,
        feedback: 'Very useful content, but a bit advanced for beginners.',
        id: '240',
    },
    {
        userId: 'Ue15ycXTpxVhCZ2eJoOVYaArKEa2',
        articleId: '37',
        rate: 5,
        feedback:
            'Superb article, provided great insights and helped improve my code.',
        id: '241',
    },
    {
        userId: 'KXv8oUPLQeUXSzoXOWJV4nw47CG2',
        articleId: '60',
        rate: 5,
        feedback:
            'Brilliant! The concepts are well explained with solid examples.',
        id: '242',
    },
    {
        userId: '18zZBJnmEqWJNwGj2SvbNiNVXol1',
        articleId: '60',
        rate: 4,
        feedback:
            'Very clear and insightful. Would love to see more practical applications.',
        id: '243',
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '60',
        rate: 5,
        feedback:
            'Loved the structure of the article. Easy to follow and informative.',
        id: '244',
    },
    {
        userId: '4juq0tzGf5fNMCXCRFOa5mvFO5O2',
        articleId: '60',
        rate: 4,
        feedback:
            'Good article, helped clarify some tough concepts. Could use more depth in some areas.',
        id: '245',
    },
    {
        userId: '9Dpc2pFoeORLyQrxHlGIbe5wjbf2',
        articleId: '104',
        rate: 5,
        feedback:
            'Fantastic explanation! One of the best articles on this topic I’ve read.',
        id: '246',
    },
    {
        userId: 'BrKES0pOcxcgYBUpKmZxBzqKFhl1',
        articleId: '104',
        rate: 4,
        feedback:
            'Good read, very helpful for understanding advanced concepts.',
        id: '247',
    },
    {
        userId: 'Ue15ycXTpxVhCZ2eJoOVYaArKEa2',
        articleId: '104',
        rate: 5,
        feedback: 'Extremely useful and well-explained. Highly recommended!',
        id: '248',
    },
    {
        userId: 'KXv8oUPLQeUXSzoXOWJV4nw47CG2',
        articleId: '104',
        rate: 5,
        feedback: 'Clear, concise, and to the point. Great job!',
        id: '249',
    },
    {
        userId: '18zZBJnmEqWJNwGj2SvbNiNVXol1',
        articleId: '120',
        rate: 5,
        feedback:
            'Top-notch article with great examples. Really helped me understand the topic.',
        id: '250',
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '120',
        rate: 4,
        feedback:
            'Well-written and easy to grasp. Would love more real-world applications.',
        id: '251',
    },
    {
        userId: '4juq0tzGf5fNMCXCRFOa5mvFO5O2',
        articleId: '120',
        rate: 5,
        feedback:
            'Really insightful and clear explanations. Great for learners!',
        id: '252',
    },
    {
        userId: '9Dpc2pFoeORLyQrxHlGIbe5wjbf2',
        articleId: '139',
        rate: 5,
        feedback: 'A solid article with well-presented information. Loved it!',
        id: '253',
    },
    {
        userId: 'BrKES0pOcxcgYBUpKmZxBzqKFhl1',
        articleId: '139',
        rate: 5,
        feedback:
            'Great article! The explanations are very thorough and useful.',
        id: '254',
    },
    {
        userId: 'Ue15ycXTpxVhCZ2eJoOVYaArKEa2',
        articleId: '139',
        rate: 4,
        feedback:
            'Very well-written and easy to follow. A bit more detail would be nice.',
        id: '255',
    },
    {
        userId: 'KXv8oUPLQeUXSzoXOWJV4nw47CG2',
        articleId: '139',
        rate: 5,
        feedback:
            'An amazing resource for this topic. Clear and comprehensive.',
        id: '256',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '34',
        rate: 1,
        feedback:
            'The article lacks clarity and proper examples. Hard to follow.',
        id: '257',
    },
    {
        userId: 'Str49JTKBAOoaEhM8XeQLLLPPDp2',
        articleId: '34',
        rate: 2,
        feedback: 'Not well-structured. The explanations are too vague.',
        id: '258',
    },
    {
        userId: 'qkcVyIbnjYeEbaYVKGhtZrny7GC3',
        articleId: '34',
        rate: 1,
        feedback:
            'Poorly written and difficult to understand. Needs a lot of improvement.',
        id: '259',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '35',
        rate: 2,
        feedback:
            "The content is shallow and doesn't cover the topic in-depth.",
        id: '260',
    },
    {
        userId: 'Str49JTKBAOoaEhM8XeQLLLPPDp2',
        articleId: '35',
        rate: 1,
        feedback: 'Disappointing. The article barely scratches the surface.',
        id: '261',
    },
    {
        userId: 'qkcVyIbnjYeEbaYVKGhtZrny7GC3',
        articleId: '35',
        rate: 1,
        feedback: 'Incomplete and poorly researched. Lacks useful information.',
        id: '262',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '59',
        rate: 2,
        feedback:
            'The article is overly simplified. Needs more depth and examples.',
        id: '263',
    },
    {
        userId: 'Str49JTKBAOoaEhM8XeQLLLPPDp2',
        articleId: '59',
        rate: 1,
        feedback: 'Not informative enough. The points are too general.',
        id: '264',
    },
    {
        userId: 'qkcVyIbnjYeEbaYVKGhtZrny7GC3',
        articleId: '59',
        rate: 2,
        feedback:
            'The article leaves a lot of questions unanswered. Needs improvement.',
        id: '265',
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '118',
        rate: 4,
        feedback:
            'Well-written, but could use more examples to clarify key points.',
        id: '266',
    },
    {
        userId: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
        articleId: '118',
        rate: 3,
        feedback: 'Good article overall, but lacks depth in some areas.',
        id: '267',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '118',
        rate: 4,
        feedback: 'Solid content, but a bit more detail would make it great.',
        id: '268',
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '131',
        rate: 3,
        feedback:
            "Decent article, but it doesn't cover all aspects of the topic.",
        id: '269',
    },
    {
        userId: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
        articleId: '131',
        rate: 4,
        feedback:
            'Good structure and flow, but more examples would be helpful.',
        id: '270',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '131',
        rate: 3,
        id: '271',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '30',
        rate: 5,
        feedback: 'Excellent explanation with detailed examples, very helpful.',
        id: '272',
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '30',
        rate: 3,
        feedback:
            'The article is okay, but could benefit from more real-world examples.',
        id: '273',
    },
    {
        userId: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
        articleId: '30',
        rate: 4,
        feedback: 'Good content, but some sections need more clarity.',
        id: '274',
    },
    {
        userId: 'meuKZ9Dc5ucUuMn72esjwMi9Azl2',
        articleId: '30',
        rate: 2,
        feedback: 'The article was too brief and lacked in-depth explanations.',
        id: '275',
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '30',
        rate: 5,
        feedback: 'Really insightful, covers the topic thoroughly.',
        id: '276',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '31',
        rate: 4,
        feedback:
            'Great article, but a few sections could use more elaboration.',
        id: '277',
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '31',
        rate: 5,
        feedback: 'Very well-written and easy to understand, excellent job!',
        id: '278',
    },
    {
        userId: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
        articleId: '31',
        rate: 3,
        feedback: 'Not bad, but I feel it missed some key points.',
        id: '279',
    },
    {
        userId: 'meuKZ9Dc5ucUuMn72esjwMi9Azl2',
        articleId: '31',
        rate: 2,
        feedback: "Too basic, didn't provide enough depth on the subject.",
        id: '280',
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '31',
        rate: 4,
        feedback: 'Solid article, useful for getting a quick overview.',
        id: '281',
    },
    {
        userId: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
        articleId: '56',
        rate: 4,
        feedback: 'Great insights, but some sections could use more examples.',
        id: '282',
    },
    {
        userId: 'meuKZ9Dc5ucUuMn72esjwMi9Azl2',
        articleId: '56',
        rate: 4,
        feedback: 'Well-written article, enjoyed the clarity of explanation.',
        id: '283',
    },
    {
        userId: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
        articleId: '88',
        rate: 4,
        feedback: 'Informative, but could be more detailed in certain areas.',
        id: '284',
    },
    {
        userId: 'meuKZ9Dc5ucUuMn72esjwMi9Azl2',
        articleId: '88',
        rate: 4,
        feedback: 'Solid content, found it useful for understanding the topic.',
        id: '285',
    },
    {
        userId: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
        articleId: '100',
        rate: 4,
        feedback: 'Nice overview, but I expected more depth.',
        id: '286',
    },
    {
        userId: 'meuKZ9Dc5ucUuMn72esjwMi9Azl2',
        articleId: '100',
        rate: 4,
        feedback:
            'Good article, but it could benefit from additional examples.',
        id: '287',
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '16',
        rate: 4,
        feedback: 'Very insightful article, learned a lot!',
        id: '288',
    },
    {
        userId: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
        articleId: '16',
        rate: 3,
        feedback: 'Good information, but it could be clearer.',
        id: '289',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '16',
        rate: 5,
        feedback: 'Excellent resource, highly recommend!',
        id: '290',
    },
    {
        userId: '18zZBJnmEqWJNwGj2SvbNiNVXol1',
        articleId: '17',
        rate: 2,
        feedback: 'Not very engaging, needs improvement.',
        id: '291',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '17',
        rate: 3,
        feedback: 'Decent read, but it felt rushed.',
        id: '292',
    },
    {
        userId: 'Str49JTKBAOoaEhM8XeQLLLPPDp2',
        articleId: '17',
        rate: 4,
        feedback: 'Informative, but could use more examples.',
        id: '293',
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '18',
        rate: 5,
        feedback: 'Incredibly helpful, thank you!',
        id: '294',
    },
    {
        userId: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
        articleId: '18',
        rate: 4,
        feedback: 'Well structured and easy to follow.',
        id: '295',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '19',
        rate: 1,
        feedback: 'I found it lacking depth.',
        id: '296',
    },
    {
        userId: '18zZBJnmEqWJNwGj2SvbNiNVXol1',
        articleId: '19',
        rate: 5,
        feedback: 'Fantastic insights, very informative!',
        id: '297',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '20',
        rate: 4,
        feedback: 'Solid article, would love to see more!',
        id: '298',
    },
    {
        userId: 'Str49JTKBAOoaEhM8XeQLLLPPDp2',
        articleId: '20',
        rate: 3,
        feedback: 'Good start, but could use more examples.',
        id: '299',
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '21',
        rate: 2,
        feedback: 'Not very clear, needed more detail.',
        id: '300',
    },
    {
        userId: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
        articleId: '21',
        rate: 5,
        feedback: 'Loved it! Very informative and clear.',
        id: '301',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '24',
        rate: 4,
        feedback: 'Great overview, thank you!',
        id: '302',
    },
    {
        userId: '18zZBJnmEqWJNwGj2SvbNiNVXol1',
        articleId: '24',
        rate: 3,
        feedback: 'Helpful, but could use more examples.',
        id: '303',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '25',
        rate: 2,
        feedback: 'Did not meet my expectations.',
        id: '304',
    },
    {
        userId: 'Str49JTKBAOoaEhM8XeQLLLPPDp2',
        articleId: '25',
        rate: 4,
        feedback: 'Very useful, learned something new.',
        id: '305',
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '26',
        rate: 5,
        feedback: 'Fantastic article, very well written!',
        id: '306',
    },
    {
        userId: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
        articleId: '26',
        rate: 3,
        feedback: 'It was okay, but not what I expected.',
        id: '307',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '27',
        rate: 4,
        feedback: 'Well done, enjoyed reading it!',
        id: '308',
    },
    {
        userId: '18zZBJnmEqWJNwGj2SvbNiNVXol1',
        articleId: '27',
        rate: 2,
        feedback: 'Could use significant improvement.',
        id: '309',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '27',
        rate: 5,
        feedback: 'Highly informative, great job!',
        id: '310',
    },
    {
        userId: 'Str49JTKBAOoaEhM8XeQLLLPPDp2',
        articleId: '27',
        rate: 3,
        feedback: 'Nice article, but I wanted more detail.',
        id: '311',
    },
    {
        userId: '4juq0tzGf5fNMCXCRFOa5mvFO5O2',
        articleId: '6',
        rate: 4,
        feedback: 'Well written and easy to understand.',
        id: '312',
    },
    {
        userId: '9Dpc2pFoeORLyQrxHlGIbe5wjbf2',
        articleId: '6',
        rate: 3,
        feedback: 'Decent article but lacking depth.',
        id: '313',
    },
    {
        userId: 'BrKES0pOcxcgYBUpKmZxBzqKFhl1',
        articleId: '6',
        rate: 5,
        feedback: 'Fantastic insights, very helpful!',
        id: '314',
    },
    {
        userId: 'Ue15ycXTpxVhCZ2eJoOVYaArKEa2',
        articleId: '46',
        rate: 4,
        feedback: 'Great overview of the topic.',
        id: '315',
    },
    {
        userId: 'KXv8oUPLQeUXSzoXOWJV4nw47CG2',
        articleId: '46',
        rate: 3,
        feedback: 'It was informative, but could be clearer.',
        id: '316',
    },
    {
        userId: '18zZBJnmEqWJNwGj2SvbNiNVXol1',
        articleId: '46',
        rate: 5,
        feedback: 'Loved this article! Very engaging.',
        id: '317',
    },
    {
        userId: '4juq0tzGf5fNMCXCRFOa5mvFO5O2',
        articleId: '9',
        rate: 4,
        feedback: 'Useful information, well structured.',
        id: '318',
    },
    {
        userId: '9Dpc2pFoeORLyQrxHlGIbe5wjbf2',
        articleId: '9',
        rate: 3,
        feedback: 'Average article, nothing new.',
        id: '319',
    },
    {
        userId: 'BrKES0pOcxcgYBUpKmZxBzqKFhl1',
        articleId: '11',
        rate: 5,
        feedback: 'Very comprehensive and well-researched.',
        id: '320',
    },
    {
        userId: 'Ue15ycXTpxVhCZ2eJoOVYaArKEa2',
        articleId: '11',
        rate: 4,
        feedback: 'Good article, I learned something new!',
        id: '321',
    },
    {
        userId: 'KXv8oUPLQeUXSzoXOWJV4nw47CG2',
        articleId: '13',
        rate: 3,
        feedback: 'It could use more examples to illustrate points.',
        id: '322',
    },
    {
        userId: '18zZBJnmEqWJNwGj2SvbNiNVXol1',
        articleId: '13',
        rate: 4,
        feedback: 'Helpful and well organized!',
        id: '323',
    },
    {
        userId: '4juq0tzGf5fNMCXCRFOa5mvFO5O2',
        articleId: '15',
        rate: 5,
        feedback: 'Excellent read, very insightful!',
        id: '324',
    },
    {
        userId: '9Dpc2pFoeORLyQrxHlGIbe5wjbf2',
        articleId: '15',
        rate: 3,
        feedback: 'Informative, but felt a bit rushed.',
        id: '325',
    },
    {
        userId: 'BrKES0pOcxcgYBUpKmZxBzqKFhl1',
        articleId: '15',
        rate: 4,
        feedback: 'Great article! Would recommend to others.',
        id: '326',
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '1',
        rate: 5,
        feedback: 'Outstanding article! Very informative and well-structured.',
        id: '401',
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '1',
        rate: 4,
        feedback: 'Great insights, but could use more examples.',
        id: '402',
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '2',
        rate: 5,
        feedback: 'Exceptional writing! I learned a lot.',
        id: '403',
    },
    {
        userId: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
        articleId: '2',
        rate: 4,
        feedback: 'Very helpful, a must-read for beginners.',
        id: '404',
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '43',
        rate: 5,
        feedback: 'A brilliant piece! Covers everything in detail.',
        id: '405',
    },
    {
        userId: '4juq0tzGf5fNMCXCRFOa5mvFO5O2',
        articleId: '43',
        rate: 4,
        feedback: 'Informative and well-researched. I appreciate the effort.',
        id: '406',
    },
    {
        userId: '9Dpc2pFoeORLyQrxHlGIbe5wjbf2',
        articleId: '3',
        rate: 5,
        feedback: 'Absolutely fantastic! I found it very engaging.',
        id: '407',
    },
    {
        userId: 'BrKES0pOcxcgYBUpKmZxBzqKFhl1',
        articleId: '3',
        rate: 4,
        feedback: 'Solid article! Clear explanations throughout.',
        id: '408',
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '4',
        rate: 5,
        feedback: "One of the best articles I've read this month!",
        id: '409',
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '4',
        rate: 4,
        feedback: 'Great content! Could benefit from more visuals.',
        id: '410',
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '44',
        rate: 5,
        feedback: 'Excellent resource! Very thorough and insightful.',
        id: '411',
    },
    {
        userId: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
        articleId: '44',
        rate: 4,
        feedback: 'Very well done! It really helped clarify things.',
        id: '412',
    },
    {
        userId: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
        articleId: '76',
        rate: 4,
        feedback:
            'Very informative article! Helped me understand the topic better.',
        id: '413',
    },
    {
        userId: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
        articleId: '143',
        rate: 3,
        feedback: 'Decent read, but I expected more detailed examples.',
        id: '414',
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '144',
        rate: 5,
        feedback: 'Exceptional insights! I learned a lot from this article.',
        id: '415',
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '145',
        rate: 4,
        feedback: 'Well-written and clear. Great resource for beginners!',
        id: '416',
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '146',
        rate: 5,
        feedback: 'Outstanding content! I appreciate the thoroughness.',
        id: '417',
    },
    {
        userId: '9Dpc2pFoeORLyQrxHlGIbe5wjbf2',
        articleId: '147',
        rate: 4,
        feedback: 'Good information, though some sections felt rushed.',
        id: '418',
    },
    {
        userId: 'Ue15ycXTpxVhCZ2eJoOVYaArKEa2',
        articleId: '116',
        rate: 3,
        feedback: 'Average article. Some points were unclear.',
        id: '419',
    },
    {
        userId: '18zZBJnmEqWJNwGj2SvbNiNVXol1',
        articleId: '129',
        rate: 5,
        feedback: 'Fantastic read! Very engaging and well-structured.',
        id: '420',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '78',
        rate: 1,
        feedback: 'The content was lacking depth and clarity.',
        id: '601',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '90',
        rate: 2,
        feedback: 'Not very useful, I expected more detailed information.',
        id: '602',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '158',
        rate: 1,
        feedback: 'This article was confusing and poorly organized.',
        id: '603',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '159',
        rate: 2,
        feedback: "Had potential, but it didn't deliver on the main points.",
        id: '604',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '161',
        rate: 1,
        feedback: 'Very disappointing. The examples were irrelevant.',
        id: '605',
    },
    {
        userId: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
        articleId: '162',
        rate: 2,
        feedback: 'Could use significant improvements. Lacked engagement.',
        id: '606',
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '83',
        rate: 5,
        feedback:
            'An excellent article! It provided great insights and was very well-written.',
        id: 701,
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '95',
        rate: 4,
        feedback: 'Good content, very informative and easy to understand.',
        id: 702,
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '111',
        rate: 5,
        feedback: 'Outstanding explanation of the topic. I learned a lot!',
        id: 703,
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '126',
        rate: 4,
        feedback:
            'Well-structured and engaging. Would definitely recommend it.',
        id: 704,
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '84',
        rate: 5,
        id: 705,
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '96',
        rate: 5,
        id: 706,
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '106',
        rate: 4,
        id: 707,
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '112',
        rate: 5,
        feedback: 'Fantastic article! It was engaging and very informative.',
        id: 708,
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '53',
        rate: 4,
        feedback:
            'Great insights! I will be using this information moving forward.',
        id: 709,
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '73',
        rate: 5,
        feedback: 'Excellent content! Very well organized and clear.',
        id: 710,
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '85',
        rate: 4,
        feedback: 'Informative and well-researched. I learned a lot!',
        id: 711,
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '97',
        rate: 5,
        feedback:
            "This was one of the best articles I've read on this subject.",
        id: 712,
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '74',
        rate: 5,
        feedback: 'Outstanding! The clarity of writing is impressive.',
        id: 713,
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '86',
        rate: 4,
        feedback:
            'Good article with valuable insights. Keep up the great work!',
        id: 714,
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '98',
        rate: 5,
        feedback: 'A must-read! It provided practical tips that I can apply.',
        id: 715,
    },
    {
        userId: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
        articleId: '114',
        rate: 4,
        feedback: 'Very informative. I appreciate the thorough research.',
        id: 716,
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '149',
        rate: 5,
        feedback:
            'Absolutely loved this article! It was insightful and well-written.',
        id: 801,
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '164',
        rate: 4,
        feedback:
            'Great information presented clearly. I found it very helpful.',
        id: 802,
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '150',
        rate: 5,
        feedback: 'Fantastic read! Engaging from start to finish.',
        id: 803,
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '165',
        rate: 4,
        feedback: 'Well structured and informative. I learned a lot from it!',
        id: 804,
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '113',
        rate: 5,
        feedback: 'Excellent insights! This is exactly what I needed.',
        id: 805,
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '133',
        rate: 4,
        feedback: 'Good content and very easy to follow. Highly recommend.',
        id: 806,
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '127',
        rate: 5,
        feedback: 'Very informative! I appreciate the depth of analysis.',
        id: 807,
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '134',
        rate: 4,
        feedback: 'Solid article! It provides practical insights and tips.',
        id: 808,
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '152',
        rate: 5,
        feedback: 'Outstanding! This article has become one of my favorites.',
        id: 809,
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '167',
        rate: 4,
        feedback: 'Very well written! It covers the topic thoroughly.',
        id: 810,
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '153',
        rate: 5,
        feedback: 'Loved it! The insights were very enlightening.',
        id: 811,
    },
    {
        userId: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
        articleId: '168',
        rate: 4,
        feedback: 'Great content! I found it really useful for my research.',
        id: 812,
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '32',
        rate: 1,
        feedback:
            'I found this article to be poorly written and lacking depth.',
        id: 901,
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '33',
        rate: 2,
        feedback:
            'Not very helpful. The information provided was vague and unclear.',
        id: 902,
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '58',
        rate: 1,
        feedback:
            "Disappointed with this article. It didn't meet my expectations.",
        id: 903,
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '102',
        rate: 2,
        feedback: 'The content felt rushed and lacked proper structure.',
        id: 904,
    },
    {
        userId: 'MqonEyICTeMapkAPyPFH7w1E5l52',
        articleId: '36',
        rate: 1,
        feedback: 'Very uninformative. I expected more from this topic.',
        id: 905,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '63',
        rate: 5,
        feedback:
            'Absolutely fantastic article! It provided great insights and was very well written.',
        id: 1101,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '151',
        rate: 5,
        feedback:
            'A must-read! The content is very relevant and easy to understand.',
        id: 1102,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '166',
        rate: 5,
        feedback:
            'This article exceeded my expectations! Great job on the details.',
        id: 1103,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '64',
        rate: 5,
        feedback: 'Very informative and engaging. I learned a lot!',
        id: 1104,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '76',
        rate: 5,
        feedback:
            'Incredible read! The author did a great job breaking down complex topics.',
        id: 1105,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '143',
        rate: 5,
        feedback:
            "One of the best articles I've read on this subject. Highly recommended!",
        id: 1106,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '144',
        rate: 5,
        feedback: 'Outstanding! Very well-researched and presented. Thank you!',
        id: 1107,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '145',
        rate: 5,
        feedback:
            'Fantastic insights! I really appreciate the depth of information provided.',
        id: 1108,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '146',
        rate: 5,
        feedback: 'Exceptional quality! This article is a valuable resource.',
        id: 1109,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '147',
        rate: 5,
        feedback: 'Loved it! The clarity and detail are impressive.',
        id: 1110,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '65',
        rate: 5,
        feedback:
            'Brilliantly written! This article provides all the necessary information.',
        id: 1111,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '77',
        rate: 5,
        feedback: 'Absolutely loved this! Engaging and very informative.',
        id: 1112,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '89',
        rate: 5,
        feedback:
            'Incredible content! Thank you for sharing such valuable information.',
        id: 1113,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '156',
        rate: 5,
        feedback:
            'Highly insightful! This article really opened my eyes to new concepts.',
        id: 1114,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '157',
        rate: 5,
        feedback: 'Superb article! I enjoyed every bit of it.',
        id: 1115,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '160',
        rate: 5,
        feedback: 'Fantastic work! A truly enlightening read.',
        id: 1116,
    },
    {
        userId: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
        articleId: '163',
        rate: 5,
        feedback:
            'Excellent! The author did a great job explaining everything.',
        id: 1117,
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '45',
        rate: 1,
        feedback:
            'Very disappointing. The content was poorly organized and not informative.',
        id: 2001,
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '66',
        rate: 1,
        feedback:
            'I expected more depth. This article felt superficial and unhelpful.',
        id: 2002,
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '47',
        rate: 1,
        feedback:
            'This was a waste of time. The points made were irrelevant and confusing.',
        id: 2003,
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '48',
        rate: 1,
        feedback:
            "Extremely unhelpful. The explanations were lacking and didn't clarify anything.",
        id: 2004,
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '49',
        rate: 1,
        feedback:
            "The article was too vague. I couldn't find any useful information.",
        id: 2005,
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '50',
        rate: 1,
        feedback:
            'Not worth reading. The writing was unclear and disorganized.',
        id: 2006,
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '51',
        rate: 1,
        feedback:
            'Very poor quality. The author seems to lack expertise on the subject.',
        id: 2007,
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '52',
        rate: 1,
        feedback:
            "I was really disappointed with this article. It didn't cover the topic properly.",
        id: 2008,
    },
    {
        userId: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
        articleId: '22',
        rate: 1,
        feedback:
            'This article was frustrating to read. It offered no valuable insights.',
        id: 2009,
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '68',
        rate: 2,
        feedback: 'The content was not very engaging and lacked depth.',
        id: 3001,
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '80',
        rate: 2,
        feedback:
            'I found the article to be somewhat useful, but overall it missed key points.',
        id: 3002,
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '92',
        rate: 2,
        feedback:
            "The explanations were unclear and didn't provide enough detail.",
        id: 3003,
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '108',
        rate: 2,
        feedback:
            'It was a decent attempt, but it fell short of my expectations.',
        id: 3004,
    },
    {
        userId: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
        articleId: '123',
        rate: 2,
        feedback: 'I appreciate the effort, but the execution was lacking.',
        id: 3005,
    },
    {
        userId: 'qkcVyIbnjYeEbaYVKGhtZrny7GC3',
        articleId: '121',
        rate: 2,
        feedback: 'The article was poorly structured and hard to follow.',
        id: 4001,
    },
    {
        userId: 'qkcVyIbnjYeEbaYVKGhtZrny7GC3',
        articleId: '140',
        rate: 2,
        feedback:
            'I expected more depth and insight; it felt very superficial.',
        id: 4002,
    },
    {
        userId: 'qkcVyIbnjYeEbaYVKGhtZrny7GC3',
        articleId: '174',
        rate: 2,
        feedback: "The content didn't meet my expectations and lacked clarity.",
        id: 4003,
    },
    {
        userId: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
        articleId: '103',
        rate: 4,
        feedback:
            'Great insights and well-researched content. I found it very informative!',
        id: 5001,
    },
    {
        userId: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
        articleId: '119',
        rate: 4,
        feedback: 'Good read! The examples provided were helpful and relevant.',
        id: 5002,
    },
    {
        userId: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
        articleId: '132',
        rate: 4,
        feedback:
            'Overall, a solid article. I appreciate the clear explanations.',
        id: 5003,
    },
    {
        userId: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
        articleId: '173',
        rate: 4,
        feedback: 'Well-written and engaging. It kept my attention throughout!',
        id: 5004,
    },
];

async function uploadRatings(ratings: ArticleRating[]) {
    try {
        // @ts-ignore
        const promises = [];
        ratings.forEach((rating) => {
            const ratingDoc = doc(ratingsCollection);
            promises.push(setDoc(ratingDoc, rating));
        });

        // @ts-ignore
        await Promise.all(promises); // Wait for all uploads to complete
        console.log('Ratings uploaded successfully!');
    } catch (error) {
        console.error('Error uploading ratings:', error);
    }
}

// async function uploadRatings(ratings: ArticleRating[]) {
//     try {
//         // @ts-ignore
//         const promises = [];
//         ratings.forEach((rating) => {
//             const ratingDoc = doc(ratingsCollection);
//             promises.push(setDoc(ratingDoc, rating));
//         });
//
//         // @ts-ignore
//         await Promise.all(promises); // Wait for all uploads to complete
//         console.log('Ratings uploaded successfully!');
//     } catch (error) {
//         console.error('Error uploading ratings:', error);
//     }
// }

const AboutPage = memo(() => {
    const { t } = useTranslation('about');
    // uploadUsers(users);
    // uploadRatings(ratings);
    return <Page data-testid="AboutPage">{t('Про сайт')}</Page>;
});

export default AboutPage;

// const users = [
//     {
//         id: 'J3aB11HdHTZW6udzrrw2ymBhIOz1',
//         username: 'mainAdmin',
//         firstname: 'Maryna',
//         lastname: 'Shavlak',
//         age: '30',
//         currency: Currency.EUR,
//         country: Country.Ukraine,
//         city: 'Kharkiv',
//         email: 'mainAdmin@gmail.com',
//         roles: [UserRole.ADMIN],
//         features: {
//             isArticleRatingEnabled: true,
//             isAppRedesigned: true,
//         },
//         jsonSettings: {
//             theme: Theme.ORANGE,
//             isFirstVisit: true,
//             settingsPageHasBeenOpen: false,
//             isArticlesPageWasOpened: true,
//         },
//         avatar: 'https://drive.google.com/thumbnail?id=1RD0jSAm8kdTLKa-Vr0daeE8T9-QcfPCa&sz=w1000',
//     },
//     {
//         id: 'vvfdFnPQMLVkrnCBjsTZcPsUq9U2',
//         username: 'mainUser',
//         firstname: 'Tetiana',
//         lastname: 'Shavlak',
//         age: '54',
//         currency: Currency.UAH,
//         country: Country.Ukraine,
//         city: 'Kyiv',
//         email: 'mainUser@gmail.com',
//         roles: [UserRole.USER],
//         features: {
//             isArticleRatingEnabled: false,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.LIGHT,
//         },
//         avatar: 'https://drive.google.com/thumbnail?id=1J1xUPYYkJeOsBTpDuf36vsV7UfxlM2uG&sz=w1000',
//     },
//     {
//         id: 'zM4UyVgfKNf2vrf5sXmBIxA5QOl2',
//         username: 'mainManager',
//         firstname: 'Maxim',
//         lastname: 'Shavlak',
//         age: '27',
//         currency: Currency.EUR,
//         country: Country.Ukraine,
//         city: 'Kyiv',
//         email: 'mainManager@gmail.com',
//         roles: [UserRole.MANAGER],
//         features: {
//             isArticleRatingEnabled: false,
//             isAppRedesigned: false,
//         },
//         avatar: 'https://st3.depositphotos.com/1071184/13782/v/450/depositphotos_137825710-stock-illustration-business-person-analyzing-financial-statistics.jpg',
//     },
//     {
//         id: 'nwPyI60mR9XWY3ozVuRGItx08PY2',
//         username: 'testuser',
//         firstname: 'Test',
//         lastname: UserRole.USER,
//         age: '45',
//         currency: Currency.EUR,
//         country: Country.Ukraine,
//         city: 'Kharkiv',
//         email: 'testuser@gmail.com',
//         roles: [UserRole.ADMIN],
//         features: {
//             isArticleRatingEnabled: true,
//             isAppRedesigned: true,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.ORANGE,
//         },
//         avatar: 'https://s1.1zoom.ru/big3/992/367659-alexfas01.jpg',
//     },
//     {
//         id: 'hdkjUiQhjoPIVMqfORNbvEHm4Wg1',
//         username: 'testuser2',
//         firstname: 'Test2',
//         lastname: 'User2',
//         age: '25',
//         currency: Currency.EUR,
//         country: Country.Ukraine,
//         city: 'Kharkiv',
//         email: 'testuser2@gmail.com',
//         roles: [UserRole.ADMIN],
//         features: {
//             isArticleRatingEnabled: false,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.ORANGE,
//         },
//         avatar: 'https://example.com/avatar6.png',
//     },
//     {
//         id: 'meuKZ9Dc5ucUuMn72esjwMi9Azl2',
//         username: 'markUser',
//         firstname: 'Mark',
//         lastname: 'Smith',
//         age: '28',
//         currency: Currency.USD,
//         country: Country.Poland,
//         city: 'Warsaw',
//         email: 'markUser@gmail.com',
//         roles: [UserRole.USER],
//         features: {
//             isArticleRatingEnabled: false,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: false,
//             theme: Theme.LIGHT,
//         },
//         avatar: 'https://example.com/avatar6.png',
//     },
//     {
//         id: 'tfs04ij0b5anHdw2qt6LghQsEfC3',
//         username: 'katyaAdmin',
//         firstname: 'Katya',
//         lastname: 'Ivanova',
//         age: '35',
//         currency: Currency.UAH,
//         country: Country.Ukraine,
//         city: 'Lviv',
//         email: 'katyaAdmin@gmail.com',
//         roles: [UserRole.ADMIN],
//         features: {
//             isArticleRatingEnabled: true,
//             isAppRedesigned: true,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.DARK,
//         },
//         avatar: 'https://example.com/avatar7.jpg',
//     },
//     {
//         id: 'd6RJwaIJmjbHTV2PdSg04DpPjWl1',
//         username: 'johnManager',
//         firstname: 'John',
//         lastname: 'Doe',
//         age: '40',
//         currency: Currency.USD,
//         country: Country.Ireland,
//         city: 'Dublin',
//         email: 'johnManager@gmail.com',
//         roles: [UserRole.MANAGER],
//         features: {
//             isArticleRatingEnabled: false,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.LIGHT,
//         },
//         avatar: 'https://example.com/avatar8.jpg',
//     },
//     {
//         id: 'MqonEyICTeMapkAPyPFH7w1E5l52',
//         username: 'annaUser',
//         firstname: 'Anna',
//         lastname: 'Koval',
//         age: '22',
//         currency: Currency.EUR,
//         country: Country.Germany,
//         city: 'Berlin',
//         email: 'annaUser@gmail.com',
//         roles: [UserRole.USER],
//         features: {
//             isArticleRatingEnabled: false,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.ORANGE,
//         },
//         avatar: 'https://example.com/avatar9.jpg',
//     },
//     {
//         id: 'ObGe2X8MNTde2RSffQgE0Jpxek72',
//         username: 'lucyAdmin',
//         firstname: 'Lucy',
//         lastname: 'Brown',
//         age: '30',
//         currency: Currency.EUR,
//         country: Country.Poland,
//         city: 'Krakow',
//         email: 'lucyAdmin@gmail.com',
//         roles: [UserRole.ADMIN],
//         features: {
//             isArticleRatingEnabled: true,
//             isAppRedesigned: true,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.LIGHT,
//         },
//         avatar: 'https://example.com/avatar10.jpg',
//     },
//     {
//         id: '4g1WI5M1XIZU6VKvIfJBG7TzMsD3',
//         username: 'alexManager',
//         firstname: 'Alex',
//         lastname: 'Johnson',
//         age: '37',
//         currency: Currency.USD,
//         country: Country.Croatia,
//         city: 'Zagreb',
//         email: 'alexManager@gmail.com',
//         roles: [UserRole.MANAGER],
//         features: {
//             isArticleRatingEnabled: false,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: false,
//             theme: Theme.DARK,
//         },
//         avatar: 'https://example.com/avatar11.jpg',
//     },
//     {
//         id: '4juq0tzGf5fNMCXCRFOa5mvFO5O2',
//         username: 'leoUser',
//         firstname: 'Leo',
//         lastname: 'Mikhailov',
//         age: '29',
//         currency: Currency.UAH,
//         country: Country.Ukraine,
//         city: 'Odessa',
//         email: 'leoUser@gmail.com',
//         roles: [UserRole.USER],
//         features: {
//             isArticleRatingEnabled: true,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.ORANGE,
//         },
//         avatar: 'https://example.com/avatar12.jpg',
//     },
//     {
//         id: '9Dpc2pFoeORLyQrxHlGIbe5wjbf2',
//         username: 'janeAdmin',
//         firstname: 'Jane',
//         lastname: 'Williams',
//         age: '33',
//         currency: Currency.USD,
//         country: Country.Ireland,
//         city: 'Cork',
//         email: 'janeAdmin@gmail.com',
//         roles: [UserRole.ADMIN],
//         features: {
//             isArticleRatingEnabled: true,
//             isAppRedesigned: true,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.DARK,
//         },
//         avatar: 'https://example.com/avatar13.jpg',
//     },
//     {
//         id: 'BrKES0pOcxcgYBUpKmZxBzqKFhl1',
//         username: 'peterManager',
//         firstname: 'Peter',
//         lastname: 'Muller',
//         age: '42',
//         currency: Currency.EUR,
//         country: Country.Germany,
//         city: 'Hamburg',
//         email: 'peterManager@gmail.com',
//         roles: [UserRole.MANAGER],
//         features: {
//             isArticleRatingEnabled: false,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.LIGHT,
//         },
//         avatar: 'https://example.com/avatar14.jpg',
//     },
//     {
//         id: 'Ue15ycXTpxVhCZ2eJoOVYaArKEa2',
//         username: 'mariaUser',
//         firstname: 'Maria',
//         lastname: 'Petrova',
//         age: '27',
//         currency: Currency.UAH,
//         country: Country.Ukraine,
//         city: 'Kyiv',
//         email: 'mariaUser@gmail.com',
//         roles: [UserRole.USER],
//         features: {
//             isArticleRatingEnabled: true,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.ORANGE,
//         },
//         avatar: 'https://example.com/avatar15.jpg',
//     },
//     {
//         id: 'KXv8oUPLQeUXSzoXOWJV4nw47CG2',
//         username: 'maxAdmin',
//         firstname: 'Max',
//         lastname: 'Gordon',
//         age: '38',
//         currency: Currency.EUR,
//         country: Country.Poland,
//         city: 'Poznan',
//         email: 'maxAdmin@gmail.com',
//         roles: [UserRole.ADMIN],
//         features: {
//             isArticleRatingEnabled: true,
//             isAppRedesigned: true,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.DARK,
//         },
//         avatar: 'https://example.com/avatar16.jpg',
//     },
//     {
//         id: '18zZBJnmEqWJNwGj2SvbNiNVXol1',
//         username: 'nickManager',
//         firstname: 'Nick',
//         lastname: 'Garcia',
//         age: '41',
//         currency: Currency.USD,
//         country: Country.Croatia,
//         city: 'Split',
//         email: 'nickManager@gmail.com',
//         roles: [UserRole.MANAGER],
//         features: {
//             isArticleRatingEnabled: false,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.LIGHT,
//         },
//         avatar: 'https://example.com/avatar17.jpg',
//     },
//     {
//         id: 'mYX7XszmZJgEUSU9eeKDJYbP7P22',
//         username: 'claraUser',
//         firstname: 'Clara',
//         lastname: 'Santos',
//         age: '32',
//         currency: Currency.EUR,
//         country: Country.Germany,
//         city: 'Munich',
//         email: 'claraUser@gmail.com',
//         roles: [UserRole.USER],
//         features: {
//             isArticleRatingEnabled: true,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.ORANGE,
//         },
//         avatar: 'https://example.com/avatar18.jpg',
//     },
//     {
//         id: 'Str49JTKBAOoaEhM8XeQLLLPPDp2',
//         username: 'tomAdmin',
//         firstname: 'Tom',
//         lastname: 'Anderson',
//         age: '36',
//         currency: Currency.USD,
//         country: Country.Ireland,
//         city: 'Galway',
//         email: 'tomAdmin@gmail.com',
//         roles: [UserRole.ADMIN],
//         features: {
//             isArticleRatingEnabled: true,
//             isAppRedesigned: true,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.DARK,
//         },
//         avatar: 'https://example.com/avatar19.jpg',
//     },
//     {
//         id: 'qkcVyIbnjYeEbaYVKGhtZrny7GC3',
//         username: 'sarahManager',
//         firstname: 'Sarah',
//         lastname: 'Cooper',
//         age: '39',
//         currency: Currency.EUR,
//         country: Country.Croatia,
//         city: 'Rijeka',
//         email: 'sarahManager@gmail.com',
//         roles: [UserRole.MANAGER],
//         features: {
//             isArticleRatingEnabled: false,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.LIGHT,
//         },
//         avatar: 'https://example.com/avatar20.jpg',
//     },
//     {
//         id: 'V4wTjlJxpYdllrdmfIaprloLcrG3',
//         username: 'danielUser',
//         firstname: 'Daniel',
//         lastname: 'Adams',
//         age: '29',
//         currency: Currency.USD,
//         country: Country.USA,
//         city: 'New York',
//         email: 'danielUser@gmail.com',
//         roles: [UserRole.USER],
//         features: {
//             isArticleRatingEnabled: false,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: false,
//             theme: Theme.LIGHT,
//         },
//         avatar: 'https://example.com/avatar21.jpg',
//     },
//     {
//         id: 'lfhMI4VQqLZZmVv3fPq0yT27NLQ2',
//         username: 'victorAdmin',
//         firstname: 'Victor',
//         lastname: 'Johnson',
//         age: '42',
//         currency: Currency.EUR,
//         country: Country.England,
//         city: 'London',
//         email: 'victorAdmin@gmail.com',
//         roles: [UserRole.ADMIN],
//         features: {
//             isArticleRatingEnabled: true,
//             isAppRedesigned: true,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.ORANGE,
//         },
//         avatar: 'https://example.com/avatar22.jpg',
//     },
//     {
//         id: 'KHODlvsuABMwBACybNV9FIIO07k1',
//         username: 'olgaManager',
//         firstname: 'Olga',
//         lastname: 'Ivanova',
//         age: '37',
//         currency: Currency.EUR,
//         country: Country.Germany,
//         city: 'Frankfurt',
//         email: 'olgaManager@gmail.com',
//         roles: [UserRole.MANAGER],
//         features: {
//             isArticleRatingEnabled: false,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.LIGHT,
//         },
//         avatar: 'https://example.com/avatar23.jpg',
//     },
//     {
//         id: 'Hrsg32Jr4uQS7P4HusvSAQ7R8Zt2',
//         username: 'emmaUser',
//         firstname: 'Emma',
//         lastname: 'Anderson',
//         age: '26',
//         currency: Currency.USD,
//         country: Country.Canada,
//         city: 'Toronto',
//         email: 'emmaUser@gmail.com',
//         roles: [UserRole.USER],
//         features: {
//             isArticleRatingEnabled: true,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.ORANGE,
//         },
//         avatar: 'https://example.com/avatar24.jpg',
//     },
//     {
//         id: 'hWB4U7cCG1VHNBWX8i7OQ0qqD0o2',
//         username: 'jasonAdmin',
//         firstname: 'Jason',
//         lastname: 'Gordon',
//         age: '45',
//         currency: Currency.USD,
//         country: Country.USA,
//         city: 'Los Angeles',
//         email: 'jasonAdmin@gmail.com',
//         roles: [UserRole.ADMIN],
//         features: {
//             isArticleRatingEnabled: true,
//             isAppRedesigned: true,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.DARK,
//         },
//         avatar: 'https://example.com/avatar25.jpg',
//     },
//     {
//         id: 'bH4QePW3zDOYqHch98cXBLlpYK52',
//         username: 'lindaManager',
//         firstname: 'Linda',
//         lastname: 'Muller',
//         age: '33',
//         currency: Currency.EUR,
//         country: Country.Austria,
//         city: 'Vienna',
//         email: 'lindaManager@gmail.com',
//         roles: [UserRole.MANAGER],
//         features: {
//             isArticleRatingEnabled: false,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: true,
//             theme: Theme.LIGHT,
//         },
//         avatar: 'https://example.com/avatar26.jpg',
//     },
//     {
//         id: 'jkoqxfXfRKUBgGQrvyL8J3QDDVm2',
//         username: 'henryUser',
//         firstname: 'Henry',
//         lastname: 'Williams',
//         age: '31',
//         currency: Currency.USD,
//         country: Country.USA,
//         city: 'San Francisco',
//         email: 'henryUser@gmail.com',
//         roles: [UserRole.USER],
//         features: {
//             isArticleRatingEnabled: false,
//             isAppRedesigned: false,
//         },
//         jsonSettings: {
//             isArticlesPageWasOpened: false,
//             theme: Theme.LIGHT,
//         },
//         avatar: 'https://example.com/avatar27.jpg',
//     },
// ];
// const usersCollection = collection(firestore, 'users');
//
// async function uploadUsers(users: User[]) {
//     try {
//         // @ts-ignore
//         const promises = [];
//         users.forEach((user) => {
//             const userDoc = doc(usersCollection);
//             promises.push(setDoc(userDoc, user));
//         });
//
//         // @ts-ignore
//         await Promise.all(promises); // Wait for all uploads to complete
//         console.log('Articles uploaded successfully!');
//     } catch (error) {
//         console.error('Error uploading articles:', error);
//     }
// }
