export const testChartData = {
    '01/2023': {
        TypeScript: 1,
        HTML: 0,
        React: 0,
        JavaScript: 3,
        CSS: 1,
    },
    '01/2024': {
        TypeScript: 0,
        HTML: 0,
        React: 1,
        JavaScript: 1,
        CSS: 0,
    },
    '01/2025': {
        TypeScript: 0,
        HTML: 1,
        React: 0,
        JavaScript: 0,
        CSS: 0,
    },
    '02/2023': {
        TypeScript: 2,
        HTML: 1,
        React: 0,
        JavaScript: 2,
        CSS: 1,
    },
    '02/2024': {
        TypeScript: 0,
        HTML: 0,
        React: 5,
        JavaScript: 2,
        CSS: 1,
    },
    '02/2025': {
        TypeScript: 0,
        HTML: 0,
        React: 0,
        JavaScript: 0,
        CSS: 0,
    },
    '03/2023': {
        TypeScript: 0,
        HTML: 4,
        React: 0,
        JavaScript: 4,
        CSS: 2,
    },
    '03/2024': {
        TypeScript: 1,
        HTML: 3,
        React: 12,
        JavaScript: 3,
        CSS: 4,
    },
    '03/2025': {
        TypeScript: 0,
        HTML: 0,
        React: 0,
        JavaScript: 0,
        CSS: 0,
    },
    '04/2023': {
        TypeScript: 2,
        HTML: 0,
        React: 4,
        JavaScript: 6,
        CSS: 0,
    },
    '04/2024': {
        TypeScript: 0,
        HTML: 0,
        React: 2,
        JavaScript: 0,
        CSS: 0,
    },
    '05/2023': {
        TypeScript: 1,
        HTML: 1,
        React: 5,
        JavaScript: 3,
        CSS: 2,
    },
    '05/2024': {
        TypeScript: 0,
        HTML: 1,
        React: 0,
        JavaScript: 2,
        CSS: 0,
    },
    '06/2023': {
        TypeScript: 1,
        HTML: 0,
        React: 5,
        JavaScript: 3,
        CSS: 1,
    },
    '06/2024': {
        TypeScript: 0,
        HTML: 0,
        React: 0,
        JavaScript: 2,
        CSS: 0,
    },
    '07/2023': {
        TypeScript: 0,
        HTML: 0,
        React: 1,
        JavaScript: 1,
        CSS: 1,
    },
    '07/2024': {
        TypeScript: 0,
        HTML: 1,
        React: 0,
        JavaScript: 3,
        CSS: 0,
    },
    '08/2023': {
        TypeScript: 1,
        HTML: 0,
        React: 1,
        JavaScript: 1,
        CSS: 2,
    },
    '08/2024': {
        TypeScript: 0,
        HTML: 1,
        React: 0,
        JavaScript: 1,
        CSS: 0,
    },
    '09/2023': {
        TypeScript: 1,
        HTML: 2,
        React: 3,
        JavaScript: 3,
        CSS: 3,
    },
    '09/2024': {
        TypeScript: 0,
        HTML: 1,
        React: 0,
        JavaScript: 4,
        CSS: 0,
    },
    '10/2023': {
        TypeScript: 0,
        HTML: 0,
        React: 0,
        JavaScript: 0,
        CSS: 0,
    },
    '10/2024': {
        TypeScript: 0,
        HTML: 1,
        React: 1,
        JavaScript: 5,
        CSS: 0,
    },
    '11/2023': {
        TypeScript: 0,
        HTML: 0,
        React: 0,
        JavaScript: 0,
        CSS: 0,
    },
    '11/2024': {
        TypeScript: 0,
        HTML: 8,
        React: 0,
        JavaScript: 5,
        CSS: 12,
    },
    '12/2023': {
        TypeScript: 1,
        HTML: 0,
        React: 6,
        JavaScript: 3,
        CSS: 0,
    },
    '12/2024': {
        TypeScript: 0,
        HTML: 0,
        React: 0,
        JavaScript: 4,
        CSS: 1,
    },
};
