/**
 * Generates a Redux slice configuration using `@reduxjs/toolkit` with TypeScript types.
 *
 * This function creates a Redux slice configuration string, including imports, initial state, and reducers.
 * The interface name is generated by capitalizing the first letter of `sliceName` and appending `Schema`.
 * The resulting slice configuration includes a placeholder for `extraReducers` that can be customized as needed.
 *
 * @param {string} sliceName - The name of the slice to be used in the Redux slice configuration. The first letter of the resulting interface name will be capitalized.
 * @return {string} The Redux slice configuration as a string, including imports, initial state, reducers, and exported actions and reducer.
 *
 * @example
 * // returns a Redux slice configuration for the 'user' slice
 * module.exports('user');
 *
 */
const firstCharUpperCase = require('../firstCharUpperCase');

module.exports = (sliceName) => {
    const typeName = `${firstCharUpperCase(sliceName)}Schema`;

    return `import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { ${typeName} } from '../types/${sliceName}Schema';

const initialState: ${typeName} = {
    
};

export const ${sliceName}Slice = createSlice({
    name: '${sliceName}',
    initialState,
    reducers: {
        template: (state, action: PayloadAction<string>) => {
           
        },
    },
    // extraReducers: (builder) => {
    //     builder
    //         .addCase(, (state) => {
    //             state.error = undefined;
    //             state.isLoading = true;
    //         })
    //         .addCase(, (state) => {
    //             state.isLoading = false;
    //         })
    //         .addCase(, (state, action) => {
    //             state.isLoading = false;
    //             state.error = action.payload;
    //         });
    // },
});

export const { actions: ${sliceName}Actions } = ${sliceName}Slice;
export const { reducer: ${sliceName}Reducer } = ${sliceName}Slice;`;
};
